Resources:
  # The federated identity for our user pool to authenticate with
  CognitoIdentityPool:
    Type: AWS::Cognito::IdenityPool
    Properties:
      IdentityPoolName: ${self:custom.stage}IdentityPool
      # don't allow unauthenticated users
      AllowUnauthenticatedIdentities: false
      # Link to our user pool
      CognitoIdentityProviders:
        - ClientId:
            Ref: CognitoUserPoolClient
          ProviderName:
            Fn::GetAtt: ["CognitoUserPool", "ProviderName"]

  # IAM roles
  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        authenticated:
          FN::GetAtt: [CognitoAuthRole, Arn]

  # IAM role for authenticated users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: CognitoIdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': authenticated
    Policies:
      - PolicyName: 'CognitoAuthorizedPolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'mobileanallytics:PutEvents'
                - 'cognito-sync:*'
                - 'cognito-identity:*'
              Resource: '*'

            # allow users to invoke our api
            - Effect: Allow
              Action:
                - 'execute-api:Invoke'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:execute-api:'
                    - Ref: AWS::Region
                    - ':'
                    - Ref: AWS::AccountId
                    - ':'
                    - Ref: ApiGatewayRestApi
                    - '/*'

            # Allow users to upload attachments to thier folder inside our S3 bucket
            - Effect: Allow
              Action:
                - 's3:*'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - Fn::GetAtt: [AttachmentsBucket, Arn]
                    - '/private/'
                    - '$'
                    - '{cognito-identity.amazonaws.com:sub}/*'

Outputs:
  IdentityPoolId:
    Value:
      Ref: CognitoIdentityPool