Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self.custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
        - AttributeName: attachment
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH # primary key can be hash or hash and range.
        -AttributeName: noteId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self.custom.tableThroughput}
        WriteCapacityUnits: ${self.custom.tableThroughput}