Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
    #CORS
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

#print the name of the bucket
Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
